mapFiles:
  - map1.txt
  - map2.txt
  
gameParams:
  dimensions:
    GAME_WIDTH: 1500
    GAME_HEIGHT: 150
  
  entities:
    PLAYER_WIDTH: 20
    PLAYER_HEIGHT: 15
    PLAYER_HEALTH: 100
    PLAYER_SPEED: 10

    INFECTED_WIDTH: 20
    INFECTED_HEIGHT: 15
    INFECTED_HEALTH: 100
    INFECTED_SPEED: 10

    JUMPER_WIDTH: 20
    JUMPER_HEIGHT: 10
    JUMPER_HEALTH: 200
    JUMPER_SPEED: 10

    WITCH_WIDTH: 20
    WITCH_HEIGHT: 15
    WITCH_HEALTH: 1000
    WITCH_SPEED: 10

    SPEAR_WIDTH: 20
    SPEAR_HEIGHT: 15
    SPEAR_HEALTH: 100
    SPEAR_SPEED: 10

    VENOM_WIDTH: 20
    VENOM_HEIGHT: 15
    VENOM_HEALTH: 250
    VENOM_SPEED: 10
    
  weapons:
    SMG_DAMAGE: 10
    RIFLE_DAMAGE: 20
    SNIPER_DAMAGE: 50
    SMG_COOLDOWN: 10
    RIFLE_COOLDOWN: 30
    SNIPER_COOLDOWN: 50
    SMG_MAX_BULLETS: 30
    RIFLE_MAX_BULLETS: 50
    SNIPER_MAX_BULLETS: 20
    SMG_BULLETS_SHOT: 10
    RIFLE_BULLETS_SHOT: 20
    SNIPER_BULLETS_SHOT: 1
