mapFiles:
  - map1.txt
  - map2.txt
  
gameParams:
  dimensions:
    GAME_WIDTH: 1500
    GAME_HEIGHT: 150
  
  entities:
    PLAYER_WIDTH: 20
    PLAYER_HEIGHT: 15
    INFECTED_WIDTH: 20
    INFECTED_HEIGHT: 15
    PLAYER_SPEED: 10
    JUMPER_WIDTH: 20
    JUMPER_HEIGHT: 10
    WITCH_WIDTH: 20
    WITCH_HEIGHT: 15
    SPEAR_WIDTH: 20
    SPEAR_HEIGHT: 15
    VENOM_WIDTH: 20
    VENOM_HEIGHT: 15
    
  weapons:
    SMG_DAMAGE: 10
    RIFLE_DAMAGE: 20
    SNIPER_DAMAGE: 50
    SMG_COOLDOWN: 10
    RIFLE_COOLDOWN: 30
    SNIPER_COOLDOWN: 50
    SMG_MAX_BULLETS: 30
    RIFLE_MAX_BULLETS: 50
    SNIPER_MAX_BULLETS: 20
    SMG_BULLETS_SHOT: 10
    RIFLE_BULLETS_SHOT: 20
    SNIPER_BULLETS_SHOT: 1
