mapFiles:
  - map1.txt
  - map2.txt
gameParams:
  SMG_DAMAGE: 10
  RIFLE_DAMAGE: 20
  SNIPER_DAMAGE: 50
  SMG_COOLDOWN: 10
  RIFLE_COOLDOWN: 30
  SNIPER_COOLDOWN: 50
  SMG_MAX_BULLETS: 30
  RIFLE_MAX_BULLETS: 50
  SNIPER_MAX_BULLETS: 20
  SMG_BULLETS_SHOT: 10
  RIFLE_BULLETS_SHOT: 20
  SNIPER_BULLETS_SHOT: 1
