mapFiles:
  - map1.txt
  - map2.txt
  
gameParams:
  dimensions:
  #la verdad que esta el tamaño del mapa para modificar aca pero no deberia de estarlo ya que romperia bastante el tema de los obstaculos, lo dejo aca por tema de tiempo pero deberian ser ctes en game esto
    GAME_WIDTH: 1500
    GAME_HEIGHT: 150
    PLAYER_MAX_AFK_TIME: 1800
  
  entities:
    PLAYER_WIDTH: 20
    PLAYER_HEIGHT: 15
    PLAYER_HEALTH: 100
    PLAYER_SPEED: 5 
    PLAYER_ATTACK_DURATION: 30
    PLAYER_RELOAD_DURATION: 30
    PLAYER_HURT_DURATION: 15
    PLAYER_DYING_DURATION: 900
    PLAYER_DEATH_DURATION: 60
    PLAYER_REVIVE_DISTANCE: 60
    PLAYER_REVIVAL_DURATION: 5

    INFECTED_WIDTH: 20
    INFECTED_HEIGHT: 15
    INFECTED_HEALTH: 100
    INFECTED_SPEED: 1
    INFECTED_ATTACK_RANGE: 30
    INFECTED_ATTACK_DAMAGE: 25
    INFECTED_ATTACK_COOLDOWN: 60
    INFECTED_HURT_DURATION: 45
    INFECTED_DYING_DURATION: 60
    INFECTED_DEATH_DURATION: 60

    JUMPER_WIDTH: 20
    JUMPER_HEIGHT: 10
    JUMPER_HEALTH: 200
    JUMPER_SPEED: 1
    JUMPER_ATTACK_RANGE: 35
    JUMPER_ATTACK_DAMAGE: 10
    JUMPER_ATTACK_COOLDOWN: 30
    JUMPER_JUMP_DAMAGE: 50
    JUMPER_JUMP_RANGE: 10
    JUMPER_JUMP_COOLDOWN: 120
    JUMPER_JUMP_DURATION: 90
    JUMPER_JUMP_DISTANCE: 500
    JUMPER_HURT_DURATION: 45
    JUMPER_DYING_DURATION: 60
    JUMPER_DEATH_DURATION: 60

    WITCH_WIDTH: 20
    WITCH_HEIGHT: 15
    WITCH_HEALTH: 500
    WITCH_SPEED: 1
    WITCH_ATTACK_RANGE: 20
    WITCH_ATTACK_DAMAGE: 100
    WITCH_ATTACK_COOLDOWN: 60
    WITCH_WAIL_COOLDOWN: 300
    WITCH_WAIL_DURATION: 30
    WITCH_HURT_DURATION: 45
    WITCH_DYING_DURATION: 60
    WITCH_DEATH_DURATION: 60

    SPEAR_WIDTH: 20
    SPEAR_HEIGHT: 15
    SPEAR_HEALTH: 100
    SPEAR_SPEED: 1
    SPEAR_ATTACK_RANGE: 50
    SPEAR_ATTACK_DAMAGE: 30
    SPEAR_ATTACK_COOLDOWN: 45
    SPEAR_HURT_DURATION: 45
    SPEAR_DYING_DURATION: 60
    SPEAR_DEATH_DURATION: 60

    VENOM_WIDTH: 20
    VENOM_HEIGHT: 15
    VENOM_HEALTH: 250
    VENOM_SPEED: 1
    VENOM_SPRAY_RANGE: 40
    VENOM_SPRAY_DAMAGE: 50
    VENOM_PROYECTILE_RANGE: 300
    VENOM_PROYECTILE_DAMAGE: 25
    VENOM_SPRAY_COOLDOWN: 90
    VENOM_PROYECTILE_COOLDOWN: 120
    VENOM_HURT_DURATION: 45
    VENOM_DYING_DURATION: 60
    VENOM_DEATH_DURATION: 60

    
  weapons:
    SMG_DAMAGE: 60
    SMG_DAMAGE_FALLOFF: 50
    RIFLE_DAMAGE: 70
    RIFLE_DAMAGE_FALLOFF: 20
    SNIPER_DAMAGE: 200
    SNIPER_DMG_LOST_PER_PIERCE: 10
    SMG_COOLDOWN: 15
    RIFLE_COOLDOWN: 15
    SNIPER_COOLDOWN: 15
    SMG_MAX_BULLETS: 30
    RIFLE_MAX_BULLETS: 50
    SNIPER_MAX_BULLETS: 1
    SMG_BULLETS_SHOT: 10
    RIFLE_BULLETS_SHOT: 20
    SNIPER_BULLETS_SHOT: 1

  spawns:
   #this will get divided by 10 in the game, 4 means a 40% increase in stats per min
    MUTATION_STRENGTH: 4
    SPAWN_INTERVAL: 150
    SPAWN_INTERVAL_DECREASE: 30
