backgrounds:
  - name: background-war1-bright-war
    path: DATA_PATH/client/render/resources/backgrounds/War1/Bright/War.png
  - name: background-war1-pale-war
    path: DATA_PATH/client/render/resources/backgrounds/War1/Pale/War.png
  - name: background-war2-bright-war
    path: DATA_PATH/client/render/resources/backgrounds/War2/Bright/War2.png
  - name: background-war2-pale-war
    path: DATA_PATH/client/render/resources/backgrounds/War2/Pale/War2.png
  - name: background-war3-bright-war
    path: DATA_PATH/client/render/resources/backgrounds/War3/Bright/War3.png
  - name: background-war3-pale-war
    path: DATA_PATH/client/render/resources/backgrounds/War3/Pale/War3.png
  - name: background-war4-bright-war
    path: DATA_PATH/client/render/resources/backgrounds/War4/Bright/War4.png
  - name: background-war4-pale-war
    path: DATA_PATH/client/render/resources/backgrounds/War4/Pale/War4.png
  - name: barras-vida
    path: DATA_PATH/client/render/resources/vida/barrasvida.png

textures:
  - name: soldier1-attack
    path: DATA_PATH/client/render/resources/Soldier_1/Attack.png
    frames: 3
  - name: soldier1-dead
    path: DATA_PATH/client/render/resources/Soldier_1/Dead.png
    frames: 4
  - name: soldier1-explosion
    path: DATA_PATH/client/render/resources/Soldier_1/Explosion.png
    frames: 9
  - name: soldier1-grenade
    path: DATA_PATH/client/render/resources/Soldier_1/Grenade.png
    frames: 9
  - name: soldier1-hurt
    path: DATA_PATH/client/render/resources/Soldier_1/Hurt.png
    frames: 3
  - name: soldier1-idle
    path: DATA_PATH/client/render/resources/Soldier_1/Idle.png
    frames: 7
  - name: soldier1-recharge
    path: DATA_PATH/client/render/resources/Soldier_1/Recharge.png
    frames: 13
  - name: soldier1-run
    path: DATA_PATH/client/render/resources/Soldier_1/Run.png
    frames: 8
  - name: soldier1-shot1
    path: DATA_PATH/client/render/resources/Soldier_1/Shot_1.png
    frames: 4
  - name: soldier1-shot2
    path: DATA_PATH/client/render/resources/Soldier_1/Shot_2.png
    frames: 4
  - name: soldier1-walk
    path: DATA_PATH/client/render/resources/Soldier_1/Walk.png
    frames: 7

  - name: jumper-attack
    path: DATA_PATH/client/render/resources/Jumper/Attack_1.png
    frames: 4
  - name: jumper-attack1
    path: DATA_PATH/client/render/resources/Jumper/Attack_1.png
    frames: 4
  - name: jumper-attack2
    path: DATA_PATH/client/render/resources/Jumper/Attack_2.png
    frames: 4
  - name: jumper-attack3
    path: DATA_PATH/client/render/resources/Jumper/Attack_3.png
    frames: 4
  - name: jumper-dead
    path: DATA_PATH/client/render/resources/Jumper/Dead.png
    frames: 5
  - name: jumper-eating
    path: DATA_PATH/client/render/resources/Jumper/Eating.png
    frames: 11
  - name: jumper-hurt
    path: DATA_PATH/client/render/resources/Jumper/Hurt.png
    frames: 5
  - name: jumper-idle
    path: DATA_PATH/client/render/resources/Jumper/Idle.png
    frames: 9
  - name: jumper-jump
    path: DATA_PATH/client/render/resources/Jumper/Jump.png
    frames: 6
  - name: jumper-run
    path: DATA_PATH/client/render/resources/Jumper/Run.png
    frames: 8
  - name: jumper-walk
    path: DATA_PATH/client/render/resources/Jumper/Walk.png
    frames: 10

  - name: spear-attack
    path: DATA_PATH/client/render/resources/Spear/Attack_1.png
    frames: 4
  - name: spear-attack1
    path: DATA_PATH/client/render/resources/Spear/Attack_1.png
    frames: 4
  - name: spear-attack2
    path: DATA_PATH/client/render/resources/Spear/Attack_2.png
    frames: 4
  - name: spear-dead
    path: DATA_PATH/client/render/resources/Spear/Dead.png
    frames: 5
  - name: spear-fall
    path: DATA_PATH/client/render/resources/Spear/Fall.png
    frames: 6
  - name: spear-hurt
    path: DATA_PATH/client/render/resources/Spear/Hurt.png
    frames: 3
  - name: spear-idle
    path: DATA_PATH/client/render/resources/Spear/Idle.png
    frames: 7
  - name: spear-protect
    path: DATA_PATH/client/render/resources/Spear/Protect.png
    frames: 2
  - name: spear-run
    path: DATA_PATH/client/render/resources/Spear/Run.png
    frames: 6
  - name: spear-run+attack
    path: DATA_PATH/client/render/resources/Spear/Run+attack.png
    frames: 5
  - name: spear-walk
    path: DATA_PATH/client/render/resources/Spear/Walk.png
    frames: 7

  - name: venom-attack
    path: DATA_PATH/client/render/resources/Venom/Attack2.png
    frames: 8
  - name: venom-shot1
    path: DATA_PATH/client/render/resources/Venom/Attack1.png
    frames: 8
  - name: venom-attack1
    path: DATA_PATH/client/render/resources/Venom/Attack1.png
    frames: 8
  - name: venom-attack1a
    path: DATA_PATH/client/render/resources/Venom/Attack1a.png
    frames: 12
  - name: venom-attack2
    path: DATA_PATH/client/render/resources/Venom/Attack2.png
    frames: 14
  - name: venom-dead
    path: DATA_PATH/client/render/resources/Venom/Dead.png
    frames: 6
  - name: venom-hurt
    path: DATA_PATH/client/render/resources/Venom/Hurt.png
    frames: 3
  - name: venom-idle
    path: DATA_PATH/client/render/resources/Venom/Idle.png
    frames: 7
  - name: venom-jump
    path: DATA_PATH/client/render/resources/Venom/Jump.png
    frames: 9
  - name: venom-run
    path: DATA_PATH/client/render/resources/Venom/Run.png
    frames: 8
  - name: venom-walk
    path: DATA_PATH/client/render/resources/Venom/Walk.png
    frames: 6

  - name: witch-attack
    path: DATA_PATH/client/render/resources/Witch/Attack_1.png
    frames: 4
  - name: witch-attack1
    path: DATA_PATH/client/render/resources/Witch/Attack_1.png
    frames: 4
  - name: witch-attack2
    path: DATA_PATH/client/render/resources/Witch/Attack_2.png
    frames: 4
  - name: witch-attack3
    path: DATA_PATH/client/render/resources/Witch/Attack_3.png
    frames: 4
  - name: witch-dead
    path: DATA_PATH/client/render/resources/Witch/Dead.png
    frames: 5
  - name: witch-hurt
    path: DATA_PATH/client/render/resources/Witch/Hurt.png
    frames: 3
  - name: witch-idle
    path: DATA_PATH/client/render/resources/Witch/Idle.png
    frames: 5
  - name: witch-jump
    path: DATA_PATH/client/render/resources/Witch/Jump.png
    frames: 6
  - name: witch-run
    path: DATA_PATH/client/render/resources/Witch/Run.png
    frames: 7
  - name: witch-scream
    path: DATA_PATH/client/render/resources/Witch/Scream.png
    frames: 5
  - name: witch-walk
    path: DATA_PATH/client/render/resources/Witch/Walk.png
    frames: 7

  - name: zombie-attack
    path: DATA_PATH/client/render/resources/Zombie/Attack_1.png
    frames: 5
  - name: zombie-attack1
    path: DATA_PATH/client/render/resources/Zombie/Attack_1.png
    frames: 5
  - name: zombie-attack2
    path: DATA_PATH/client/render/resources/Zombie/Attack_2.png
    frames: 4
  - name: zombie-attack3
    path: DATA_PATH/client/render/resources/Zombie/Attack_3.png
    frames: 5
  - name: zombie-bite
    path: DATA_PATH/client/render/resources/Zombie/Bite.png
    frames: 11
  - name: zombie-dead
    path: DATA_PATH/client/render/resources/Zombie/Dead.png
    frames: 5
  - name: zombie-hurt
    path: DATA_PATH/client/render/resources/Zombie/Hurt.png
    frames: 3
  - name: zombie-idle
    path: DATA_PATH/client/render/resources/Zombie/Idle.png
    frames: 8
  - name: zombie-jump
    path: DATA_PATH/client/render/resources/Zombie/Jump.png
    frames: 8
  - name: zombie-run
    path: DATA_PATH/client/render/resources/Zombie/Run.png
    frames: 7
  - name: zombie-walk
    path: DATA_PATH/client/render/resources/Zombie/Walk.png
    frames: 8

translations:
  typeEntity:
    JUMPER: jumper
    SPEAR: spear
    VENOM: venom
    WITCH: witch
    ZOMBIE: zombie
    SOLDIER1: soldier1
    SOLDIER2: soldier2
    SOLDIER3: soldier3
  state:
    WALKING: walk
    RUNNING: run
    IDLE: idle
    DEAD: dead
    ATTACKING: attack
    HURTING: hurt
    EXPLOSION: explosion
    RECHARGING: recharge
    THROWING_GRENADE: grenade
    SHOT1: shot1
    SHOT2: shot2
