rendererParams:
  dimensionsWindows:
    WINDOW_WIDTH: 1400
    WINDOW_HEIGHT: 800
    GAME_HEIGHT: 150
    GAME_WIDTH: 1500
    IMAGE_BORDER_PADDING: 40

  dimensionsLifeBar:
    LIFE_BAR_WIDTH: 20
    LIFE_BAR_HEIGHT: 50
    DIST_X_LIFE_BAR_TO_ENTITY_LOOKING_LEFT: 100
    DIST_X_LIFE_BAR_TO_ENTITY_LOOKING_RIGHT: 30
    DIST_Y_LIFE_BAR_TO_ENTITY: 30

    MAX_HEALTH_SOLDIER: 100
    LIFE_LEVELS_SOLDIER: 10


